config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { registrations: 'registrations' }, path_prefix: "my"
  resources :users, only: [:show, :index, :edit, :update]

  get 'admin/dashboard'
  get 'admin/store_manager'
  get 'admin/blogs'
  get 'admin/freebies'
  get 'admin/drafts'
  get 'admin/users'
  get 'admin/categories'
  get 'admin/messages'

  get 'home/old'
  get 'home/old2'

  resources :categories
  resources :messages
  post "messages/:id/mark_answered" => "messages#mark_answered", as: "mark_answered"
  post "messages/:id/mark_unanswered" => "messages#mark_unanswered", as: "mark_unanswered"


  resources :meals
  post "meals/:id/favorite" => "meals#favorite", as: "favorite_meal"
  post "meals/:id/unfavorite" => "meals#unfavorite", as: "unfavorite_meal"

  post 'recipes/search' => 'recipes#index', as: "recipes_search"
  resources :recipes

  post "users/:id/approve_contributor" => "users#approve_contributor", as: "approve_contributor"
  post "users/:id/make_contributor" => "users#make_contributor", as: "make_contributor"
  post "users/:id/approve_sm" => "users#approve_sm", as: "approve_sm"

  get 'home/index'
  get 'home/house'
  get 'home/spouse'
  get 'home/kids'
  get 'home/self'
  get 'home/tools'
  get 'home/results'
  get 'home/redirect'

  resources :subcategories

  get 'tags/:tag', to: 'blogs#index', as: :tag
  resources :blogs do
    collection do
      get :autocomplete
    end
  end
  post "blogs/:id/approve_blog" => "blogs#approve_blog", as: "approve_blog"
  post "blogs/:id/unsubmit_blog" => "blogs#unsubmit_blog", as: "unsubmit_blog"
  patch "blogs/:id/update_goody" => "blogs#update_goody", as: "update_goody"
  patch "blogs/:id/toggle_category" => "blogs#toggle_category", as: "toggle_category"

  resources :tasks do
    collection do
      patch :sort
    end
  end
  post "tasks/:id/check_task" => "tasks#check_task", as: "check_task"
  post "tasks/:id/uncheck_task" => "tasks#uncheck_task", as: "uncheck_task"

  resources :occasions
  resources :people
  resources :gifts, only: [:edit, :update, :destroy, :show]

  resources :contributions
  post "contributions/:id/replied_contribution" => "contributions#replied_contribution", as: "replied_contribution"
  post "contributions/:id/unreplied_contribution" => "contributions#unreplied_contribution", as: "unreplied_contribution"

  resources :capsules do
    resources :capsule_items
  end

  resources :freebies
  resources :solutions

  resources :preauthorizations
  resources :sortings
  resources :groupings


  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get



end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  # belongs_to :category

  has_many :subcategorization_blogs
  has_many :blogs, through: :subcategorization_blogs

  has_many :subcategorization_freebies
  has_many :freebies, through: :subcategorization_freebies

  has_many :subcategorization_solutions
  has_many :solutions, through: :subcategorization_solutions
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]


  def index
    @subcategories = Subcategory.order('name ASC')
  end


  def show
  end


  def new
    @subcategory = Subcategory.new
  end


  def edit
  end


  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to subcategories_path, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to subcategories_path, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end


    def subcategory_params
      params.require(:subcategory).permit(
        :name,
        :active,
        :i_statement,
        :cta,
        :cta_desc,
        :description,
        :intro,
        :bad_adjective,
        :good_adjective,
        :main_photo_url,
        :photo_2_url,
        :photo_3_url,
        :freebie_id,
        :category_id,
        blog_ids: [],
        freebie_ids: [],
        solution_ids: []
      )
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= simple_form_for(@subcategory) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <h2>The Basics</h2>
    <div class="row mx-5 mb-5 py-4 bg-white z-depth-3">
      <div class="col-12">
        <%= f.input :name, placeholder: "Works with 'your ____'..." %>
        <%= f.input :active %>
      </div> <!-- col -->

      <div class="col-12 form-group">
        <% category_collection = [] %>
        <% Category.where(active: true).each do |category| %>
          <% category_collection << ["#{category.name}", "#{category.id}"] %>
        <% end %>
        <%= f.label "Primary Category (REQUIRED)" %>
        <%= f.input :category_id, label: false, prompt: "Choose a Primary Category", input_html: { class: 'browser-default' }, collection: category_collection, required: false %>
      </div>


      <div class="col-sm-12">
        <%= f.input :i_statement %>
      </div> <!-- col -->
      <div class="col-sm-6">
        <%= f.input :bad_adjective %>
      </div> <!-- col -->
      <div class="col-sm-6">
        <%= f.input :good_adjective %>
      </div> <!-- col -->
    </div> <!-- row -->



    <h2>Top Lead Magnet</h2>
    <div class="row mx-5 mb-5 py-4 bg-white z-depth-3">
      <div class="col-sm-6">
        <%= f.input :cta %>
      </div> <!-- col -->
      <div class="col-sm-6 form-group">
        <% freebie_collection = [] %>
        <% Freebie.where(active: true).each do |freebie| %>
          <% freebie_collection << ["#{freebie.name}", "#{freebie.id}"] %>
        <% end %>
        <%= f.label "Lead Magnet (REQUIRED)" %>
        <%= f.input :freebie_id, label: false, prompt: "Choose a Related Freebie", input_html: { class: 'browser-default' }, collection: freebie_collection, required: true %>
      </div>
      <div class="col-sm-12">
        <%= f.input :cta_desc %>
      </div> <!-- col -->
    </div> <!-- row -->





    <h2>Long-Winded Ramblings</h2>
    <div class="row mx-5 mb-5 py-4 bg-white z-depth-3">
      <div class="col-12">
        <%= f.input :description %>
      </div> <!-- col -->
      <div class="col-12 tinymce mb-3">
        <%= f.label "Introduction" %>
        <%= f.text_area :intro, class: "tinymce", rows: 20, style: "width: 100%" %>
      </div> <!-- col -->
    </div> <!-- row -->




    <h2>Images</h2>
    <div class="row mx-5 mb-5 py-4 bg-white z-depth-3">
      <div class="col-sm-4">
        <%= f.input :main_photo_url %>
      </div> <!-- col -->
      <div class="col-sm-4">
        <%= f.input :photo_2_url %>
      </div> <!-- col -->
      <div class="col-sm-4">
        <%= f.input :photo_3_url %>
      </div> <!-- col -->
    </div> <!-- row -->


    <h2>Products</h2>
    <div class="mx-5 mb-5 bg-white z-depth-3" style="height: 300px; overflow-y: scroll;">
      <div class="form-group form-check jsItUp">
        <%= f.collection_check_boxes(:solution_ids, Solution.all, :id, :name ) %>
      </div>
    </div>


    <h2>Quick Fixes</h2>
    <div class="mx-5 mb-5 bg-white z-depth-3" style="height: 300px; overflow-y: scroll;">
      <div class="form-group form-check jsItUp">
        <%= f.collection_check_boxes(:freebie_ids, Freebie.all, :id, :name ) %>
      </div>
    </div>



    <h2>Blogs</h2>
    <div class="mx-5 mb-5 bg-white z-depth-3" style="height: 300px; overflow-y: scroll;">
      <div class="form-group form-check jsItUp">
        <%= f.collection_check_boxes(:blog_ids, Blog.where(nondisplayed: false), :id, :title ) %>
      </div>
    </div>



  </div> <!-- form inputs -->

  <div class="form-actions text-center pt-4">
    <%= f.button :submit, class: "btn-pink" %>
  </div>
<% end %>




<%= content_for :additional_js_partial do %>
  <%= tinymce_assets %>
  <%= tinymce plugins: ["wordcount", "code", "anchor", "casechange", "codesample", "hr", "link", "preview"] %>

  <script type="text/javascript">
    $(document).ready(function() {
      $(".jsItUp input").before("<br>");
      $(".jsItUp input").addClass("form-check-input");
      $(".jsItUp label").addClass("form-check-label");
    });
  </script>
<% end %>

app/views/subcategories/edit.html.erb
<div class="container my-5">

  <h1 class="text-center font-script color-pink">Edit Subcategory</h1>

  <%= render 'form', subcategory: @subcategory %>

</div> <!-- container -->

app/views/subcategories/index.html.erb
<div class="container">
  <% if current_user && current_user.admin %>
    <p class="text-right"><%= link_to 'New Subcategory', new_subcategory_path %></p>
  <% end %>

  <section class="py-3">
    <h1 class="text-center font-script">Subcategories</h1>
    <table>
      <tbody>
        <% @subcategories.each do |subcategory| %>
          <tr>
            <td>
              <img src="<%= subcategory.main_photo_url %>" style="width: 100px; height: auto; margin-bottom: 15px; box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23); padding: 3px" >
            </td>
            <td>
              <%= link_to subcategory.name, subcategory, class: "color-pink boldest" %> (<%= Blog.where(subcategory_id: subcategory.id, published: true).count %>)<br />
              <%= subcategory.description %><br />
              <span class="boldest"><%= if subcategory.active then "Active" else "Inactive" end %></span>&nbsp; | &nbsp;
              <%= link_to 'Edit', edit_subcategory_path(subcategory) %>&nbsp; | &nbsp;
              <%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>


  <section class="py-3">
    <h1 class="text-center font-script">Uncategorized Blogs</h1>
    <ul>
      <% Blog.all.each do |blog| %>
        <% if Subcategory.where(id: blog.subcategory_id).count == 0 %>
          <li><%= link_to blog.title, blog %></li>
        <% end %>
      <% end %>
    </ul>
  </section>

</div> <!-- container -->

app/views/subcategories/new.html.erb
<div class="container my-5">

  <h1 class="text-center font-script color-pink">New Subcategory</h1>

  <%= render 'form', subcategory: @subcategory %>

</div> <!-- container -->

app/views/subcategories/show.html.erb
<main>

    <section class="masthead texture-leaves">
        <div class="container px-xl-5">
            <div class="row gx-5 p-md-0 align-items-center">

              <% if current_user && current_user.admin %>
                <div class="col-12 text-right" style="margin-top: -30px;">
            <%= link_to 'Edit Category', edit_category_path(@subcategory) %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Category Admin Page', admin_categories_path %>
          </div>
        <% end %>

                <div class="col-md-6 text-center mb-5">
                    <h1 class="display-1 lh-1"><%= @subcategory.i_statement %></h1>
                    <h3><%= @subcategory.description %></h3>
                </div>
                <div class="col-md-6 text-center">
                    <img class="classy-pic extra tilt-right" src="<%= @subcategory.main_photo_url %>">
                </div>
                 <div class="col-12 text-center">
                   <%= link_to @subcategory.cta, Freebie.find(@subcategory.freebie_id), class: "btn btn-pink btn-lg mt-5" %>
                </div>

      </div>
        </div>
    </section>



    <section class="z-over bg-white z-depth-2-y py-5">
      <div class="container">
        <h2 class="display-1 color-pink font-script text-center">
          <%= @subcategory.good_adjective %>, not <%= @subcategory.bad_adjective.downcase %>.
        </h2>
        <div class="text-center">
                <img class="classy-pic tilt-left w-50 mb-5" src="<%= @subcategory.photo_2_url %>">
            </div>
        <%= raw(@subcategory.intro) %>
      </div>
    </section>



    <section class="z-under py-5">
      <div class="container">
        <div class="text-center">
                <h2 class="pb-4">How to <%= @subcategory.cta.titleize %></h2>
        </div> <!-- col -->

        <div class="row align-items-center">

          <div class="col-sm-6 text-center">
                  <img class="classy-pic tilt-left mb-5 w-75" src="<%= @subcategory.photo_3_url %>">
          </div> <!-- col -->

          <div class="col-sm-6">
                  <p class="h3"><%= @subcategory.cta_desc %></p>
                    <%= Freebie.find(@subcategory.freebie_id).thrivelink.html_safe %>
          </div> <!-- col -->
        </div> <!-- row -->
      </div> <!-- container -->
    </section>


    <% freebie_categorizations = CategorizationFreebie.where(category_id: @subcategory.id) %>
    <% if freebie_categorizations.count != 0 %>
        <section class="z-over bg-white z-depth-2-y py-5">
            <div class="container">
                <div class="row">
                    <h2 class="display-1 color-pink font-script text-center">
                        Quick Fixes for Your <%= @subcategory.name %>
                    </h2>
                    <% freebie_categorizations.each do |categorization| %>
                        <% freebie = Freebie.find(categorization.freebie_id) %>
                            <%= render partial: "freebies/card", locals: { freebie: freebie } %>
                    <% end %>
                </div> <!-- row -->
            </div>
        </section>
    <% end %>


    <% blog_categorizations = CategorizationBlog.where(category_id: @subcategory.id) %>
    <% if blog_categorizations.count != 0 %>
        <section class="z-under py-5">
            <div class="container">
                <div class="row">
                    <h2 class="display-1 color-pink font-script text-center">
                        More about <%= @subcategory.name %>
                    </h2>
                    <% blog_categorizations.each do |categorization| %>
                        <% blog = Blog.find(categorization.blog_id) %>
                        <%= render partial: "layouts/mdbcard", locals: { blog: blog } %>
                    <% end %>
                </div> <!-- row -->
            </div>
        </section>
    <% end %>

</main>