config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { registrations: 'registrations' }, path_prefix: "my"
  resources :users, only: [:show, :index, :edit, :update]

  get 'admin/dashboard'
  get 'admin/store_manager'
  get 'admin/blogs'
  get 'admin/freebies'
  get 'admin/drafts'
  get 'admin/users'
  get 'admin/categories'
  get 'admin/messages'

  get 'home/old'
  get 'home/old2'

  resources :categories
  resources :messages
  post "messages/:id/mark_answered" => "messages#mark_answered", as: "mark_answered"
  post "messages/:id/mark_unanswered" => "messages#mark_unanswered", as: "mark_unanswered"


  resources :meals
  post "meals/:id/favorite" => "meals#favorite", as: "favorite_meal"
  post "meals/:id/unfavorite" => "meals#unfavorite", as: "unfavorite_meal"

  post 'recipes/search' => 'recipes#index', as: "recipes_search"
  resources :recipes

  post "users/:id/approve_contributor" => "users#approve_contributor", as: "approve_contributor"
  post "users/:id/make_contributor" => "users#make_contributor", as: "make_contributor"
  post "users/:id/approve_sm" => "users#approve_sm", as: "approve_sm"

  get 'home/index'
  get 'home/house'
  get 'home/spouse'
  get 'home/kids'
  get 'home/self'
  get 'home/tools'
  get 'home/results'
  get 'home/redirect'

  resources :subcategories

  get 'tags/:tag', to: 'blogs#index', as: :tag
  resources :blogs do
    collection do
      get :autocomplete
    end
  end
  post "blogs/:id/approve_blog" => "blogs#approve_blog", as: "approve_blog"
  post "blogs/:id/unsubmit_blog" => "blogs#unsubmit_blog", as: "unsubmit_blog"
  patch "blogs/:id/update_goody" => "blogs#update_goody", as: "update_goody"
  patch "blogs/:id/toggle_category" => "blogs#toggle_category", as: "toggle_category"

  resources :tasks do
    collection do
      patch :sort
    end
  end
  post "tasks/:id/check_task" => "tasks#check_task", as: "check_task"
  post "tasks/:id/uncheck_task" => "tasks#uncheck_task", as: "uncheck_task"

  resources :occasions
  resources :people
  resources :gifts, only: [:edit, :update, :destroy, :show]

  resources :contributions
  post "contributions/:id/replied_contribution" => "contributions#replied_contribution", as: "replied_contribution"
  post "contributions/:id/unreplied_contribution" => "contributions#unreplied_contribution", as: "unreplied_contribution"

  resources :capsules do
    resources :capsule_items
  end

  resources :freebies
  resources :solutions

  resources :preauthorizations
  resources :sortings
  resources :groupings


  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get



end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable_on :tags

  belongs_to :user

  belongs_to :freebie, optional: true

  has_many :categorization_blogs
  has_many :categories, through: :categorization_blogs

  has_many :subcategorization_blogs
  has_many :subcategories, through: :subcategorization_blogs

  has_one_attached :image
  has_many_attached :pin_image
  has_one_attached :pdf

  searchkick text_start: [:title], suggest: [:title]

  def search_data
    {
      title: title,
      teaser: teaser,
      body: body,
      tag_list: tag_list
    }
  end
end

app/models/capsule.rb
class Capsule < ApplicationRecord
  belongs_to :user
  has_many :capsule_items
end

app/models/capsule_item.rb
class CapsuleItem < ApplicationRecord
  belongs_to :user
  belongs_to :capsule
  has_one_attached :photo
end

app/models/category.rb
class Category < ApplicationRecord
  # has_many :subcategories
  
  has_many :categorization_blogs
  has_many :blogs, through: :categorization_blogs

  has_many :categorization_freebies
  has_many :freebies, through: :categorization_freebies

  has_many :categorization_solutions
  has_many :solutions, through: :categorization_solutions
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  
end

app/models/freebie.rb
class Freebie < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_one_attached :image
  has_one_attached :sample_image
  has_one_attached :t1_image
  has_one_attached :fb_share_image
  has_many_attached :pin_image

  has_many :blogs
  
  has_many :categorization_freebies
  has_many :categories, through: :categorization_freebies

  has_many :subcategorization_freebies
  has_many :subcategories, through: :subcategorization_freebies
end

app/models/gift.rb
class Gift < ApplicationRecord
  # Validations
  validates_presence_of :person, :occasion

  # Relations
  belongs_to :user, optional: true
  belongs_to :occasion
  belongs_to :person

  after_create :set_user_id

  private
  def set_user_id
    self.update_column(:user_id, self.occasion.user_id)
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/occasion.rb
class Occasion < ApplicationRecord
  # Relations
  has_many :gifts, dependent: :destroy
  has_many :people, through: :gifts
  belongs_to :user
end

app/models/person.rb
class Person < ApplicationRecord
  # Relations
  belongs_to :user
  has_many :gifts
  has_many :occasions, through: :gifts

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :comment, optional: true
end

app/models/solution.rb
class Solution < ApplicationRecord
  has_one_attached :image
  has_one_attached :fb_share_image
  has_one_attached :t1_image
  has_many_attached :pin_image


  has_many :categorization_solutions
  has_many :categories, through: :categorization_solutions

  has_many :subcategorization_solutions
  has_many :subcategories, through: :subcategorization_solutions

end

app/models/sorting.rb
class Sorting < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  # belongs_to :category

  has_many :subcategorization_blogs
  has_many :blogs, through: :subcategorization_blogs

  has_many :subcategorization_freebies
  has_many :freebies, through: :subcategorization_freebies

  has_many :subcategorization_solutions
  has_many :solutions, through: :subcategorization_solutions
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one_attached :avatar

  # Relations
  has_many :blogs
  has_many :tasks
  has_many :comments, dependent: :destroy
  has_many :people
  has_many :occasions
  has_many :capsules
  has_many :capsule_items
  has_many :meals
  has_many :purchases

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/admin/_blog_row.html.erb
<td>
  <div style="min-width: 150px">
    <%= link_to blog.title, blog_path(blog.id) %>
    <br><%= link_to blog.user.first_name + " " + blog.user.last_name, user_path(blog.user), class: "thin" %>
    <br>
    <%= link_to edit_blog_path(blog) do %><%= fa_icon "pencil-alt" %><% end %>
    <%= link_to blog, method: :delete, data: { confirm: 'Are you sure?' } do %><%= fa_icon "trash" %><% end %>
  </div> 
</td>

<td style="min-width: 150px" id="goody_cell<%= blog.id %>">
  <%= render partial: "admin/goody_cell", locals: { blog: blog } %>
</td>

<td>
  <span class="disqus-comment-count" data-disqus-identifier="<%= blog.id %>" data-disqus-url="<%= polymorphic_url(blog) %>">See Comments</span><br />
</td>

<td>
  <%= blog.category %>
</td>

<div>
  <%= render partial: "admin/category_cells", locals: { blog: blog } %>
</div>

<td>
  <% if Subcategory.where(id: blog.subcategory_id) != [] %>
  <%= Subcategory.where(id: blog.subcategory_id).first.name %>
  <% end %>
</td>
<td>
  <% if blog.published %>
    <% if blog.published_on %>
      <%= blog.published_on.in_time_zone("America/Los_Angeles").strftime("%-m/%-d/%y") %><br />
    <% else %>
      <i class="fas fa-check"></i>
    <% end %>
  <% else %>
    <i class="fas fa-times"></i>
  <% end %>
</td>

app/views/admin/_category_cells.html.erb
<td>
  <% if blog.house %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "house", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/1+++House.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "house", value: true), method: :patch, remote: true %>
  <% end %>
</td>
<td>
  <% if blog.pregnancy %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "pregnancy", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/3+++Pregnancy.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "pregnancy", value: true), method: :patch, remote: true %>
  <% end %>
</td>
<td>
  <% if blog.babies %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "babies", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/4+++Babies.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "babies", value: true), method: :patch, remote: true %>
  <% end %>
</td>
<td>
  <% if blog.toddlers %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "toddlers", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/5+++Toddlers.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "toddlers", value: true), method: :patch, remote: true %>
  <% end %>
</td>
<td>
  <% if blog.kids %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "kids", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/6+++Kids.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "kids", value: true), method: :patch, remote: true %>
  <% end %>
</td>
<td>
  <% if blog.teens %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "teens", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/7+++Teens.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "teens", value: true), method: :patch, remote: true %>
  <% end %>
</td>
<td>
  <% if blog.balance %>
    <%= link_to toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "balance", value: false), method: :patch, remote: true do %>
      <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Stick+Figures/8+++Balance.png" style="height: 20px">
    <% end %>
  <% else %>
    <%= link_to "--", toggle_category_path(controller: "blogs", action: "toggle_category", method: :patch, id: blog.id, category: "balance", value: true), method: :patch, remote: true %>
  <% end %>
</td>

app/views/admin/_goody_cell.html.erb
<% if blog.freebie_id %>
  <%= Freebie.find(blog.freebie_id).name %>
<% end %>

<%#= simple_form_for blog, :url => { controller: 'blogs', action: 'update_goody', method: :patch, :authenticity_token => true, :remote => true } do |f|%>
<%= simple_form_for blog, :url => update_goody_path(blog), method: :patch, authenticity_token: true, remote: true do |f| %>
  <% freebie_collection = [] %>
  <% Freebie.all.each do |lm| %>
    <% freebie_collection << ["#{lm.name}", "#{lm.id}"] %>
  <% end %>
  <div class="row text-left">
    <div class="form-group col-12 mb-0 pb-0">
      <%= f.input :freebie_id, label: false, prompt: "Choose a Related LM", input_html: { id: "lmFor" + blog.id.to_s, class: 'browser-default', onchange: "this.form.submit();" }, collection: freebie_collection, required: false %>
    </div>
  </div> <!-- row -->
<% end %>

app/views/admin/categories.html.erb
<main>
  <header class="text-center">
    <h1 class="font-script color-pink display-1 mt-3 mb-0">Categories</h1>
    <p><small>
      <%= link_to "Create a New Category", new_category_path %>
      &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to "Public Category Page", new_category_path %>
    </small></p>
  </header>

</main>


<section class="container">
  <% @categories.each do |category| %>
    <div class="content-box mb-3">
      <h2 class="text-center"><%= link_to category.name, category_path(category) %>
        <% unless category.active %> (Inactive)<% end %>
      </h2>
      <p><%= category.description %><p>
      <p>
        <strong>Adjectives: </strong>
        <%= category.bad_adjective %> / <%= category.good_adjective %>
      <br>
        <strong>I Statement: </strong>
        <%= category.i_statement %>
      <br>
        <strong>CTA: </strong>
        <%= category.cta %>
      <br><small><em>
        <%= link_to 'Edit', edit_category_path(category) %> | <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
      </em></small></p>
    </div>
  <% end %>
</section>

app/views/admin/drafts.html.erb
<main class="container">

  <header class="text-center pt-3">
    <h1 class="display-1 font-script color-pink">My Blogs</h1>
  </header>

  <section id="drafts" class="bg-white z-depth-3 p-3 mb-5">
    <h2 class="h4 text-center pb-3">Drafts and Submissions (<%= Blog.where(user_id: current_user.id, published: false).count %>)</h2>
    <table id="draftsTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="th-sm">#
          </th>
          <th class="th-sm">Title
          </th>
          <th class="th-sm">Status
          </th>
          <th class="th-sm">Date Started
          </th>
        </tr>
      </thead>
      <tbody>
        <% @blogs.each do |blog| %>
          <% unless blog.published %>
            <tr>
              <td><%= blog.id %></td>
              <td>
                <%= link_to blog.title, blog_path(blog) %>
                <% unless blog.submitted %>
                  <%= link_to "(Edit)", edit_blog_path(blog) %>
                <% end %>
              </td>
              <td>
                <% if blog.submitted %>
                  Submitted
                <% else %>
                  Draft
                <% end %>
              </td>
              <td><%= blog.created_at.strftime("%m/%d/%Y") %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </section>



  <section id="published" class="bg-white z-depth-3 p-3 my-5">
    <h2 class="h4 text-center pb-3">Published Articles (<%= Blog.where(user_id: current_user.id, published: true).count %>)</h2>
    <table id="publishedTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th class="th-sm">#
          </th>
          <th class="th-sm">Title
          </th>
          <th class="th-sm">Date Published
          </th>
          <th class="th-sm">Date Started
          </th>
        </tr>
      </thead>
      <tbody>
        <% @blogs.each do |blog| %>
          <% if blog.published %>
            <tr>
              <td><%= blog.id %></td>
              <td><%= link_to blog.title, blog_path(blog) %></td>
              <td>
                <%= blog.published_on.strftime("%m/%d/%Y") %>
              </td>
              <td><%= blog.created_at.strftime("%m/%d/%Y") %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </section>


</main>




<script>
  $(document).ready(function () {
    $('#publishedTable').DataTable();
    $('#draftsTable').DataTable();
    $('.dataTables_length').addClass('bs-select');
  });
</script>

app/views/admin/messages.html.erb
<%= content_for :title do %>
  Messages
<% end %>


<section class="breadcrumbs px-4 py-3">
  <p>
    <%= link_to "Admin Dashboard", admin_dashboard_path %>
    &nbsp;&nbsp;>&nbsp;&nbsp;
    Messages
  </p>
</section>


<main class="container pb-5">

  <header class="text-center">
    <h1 class="bolder color-midnight">Messages</h1>
  </header>

  <section>
      <% message_type_array = [] %>
      <% @messages.each do |message| %>
        <% unless message_type_array.include? message.message_type %>
          <% message_type_array.unshift(message.message_type) %>
        <% end %>
      <% end %>
      <% message_type_array.each do |message_type| %>
        <h3><%= message_type %></h3>
        <% @messages.each do |message| %>
          <% if message.message_type == message_type %>
            <div class="content-box bg-white">
              <%= render partial: "messages/show", locals: { message: message } %>
            </div>
          <% end %>
        <% end %>
      <% end %>
  </section>

</main>

app/views/admin/users.html.erb
<main class="mb-5 container">
  <header class="text-center mt-3">
    <h1 class="font-script color-pink">Users and Superusers</h1>
  </header>


  <section class="text-center mb-5 my-"> <!-- admin -->
    <h2 id="superuser-header">Superusers</h2>
    <div id="superuser-container">

      <div class="table-responsive" style="width: 100%">
        <table id="tableSuperusers" class="table thin table-striped table-bordered" width="100%">
          <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
              <th>Contributor</th>
              <th>Admin</th>
              <th>Since</th>
              <th><i class="fas fa-times"></i></th>
            </tr>
          </thead>

          <tbody class="text-left">
            <% @superusers.each do |user| %>
              <tr>
                <td><%= user.full_name %></td>
                <td><%= mail_to user.email, user.email, target: "_blank" %></td>
                <td class="text-center"><% if user.contributor %><i class="fas fa-check"></i><% end %></td>
                <td class="text-center"><% if user.admin %><i class="fas fa-check"></i><% end %></td>
                <td><%= user.created_at.year %></td>
                <th class="text-center"><%= link_to '<i class="fas fa-times"></i>'.html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } %></th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> <!-- table responsive -->

    </div> <!-- superuser container -->
  </section>








  <section class="text-center mb-5 my-"> <!-- admin -->
    <h2 id="preauthorization-header">Preauthorizations</h2>
    <div id="preauthorization-container">

      <button type="button" class="btn btn-pink btn-sm mb-3" data-toggle="modal" data-target="#newPreauthorization">
        New Preauthorization
      </button>

      <div class="table-responsive" style="width: 100%">
        <table id="tablePreauthorizations" class="table thin table-striped table-bordered" width="100%">
          <thead>
            <tr>
              <th>Email</th>
              <th>Admin</th>
              <th>Contributor</th>
              <th>Account Created</th>
              <th><i class="fas fa-times"></i></th>
            </tr>
          </thead>

          <tbody class="text-left">
            <% @preauthorizations.each do |preauthorization| %>
              <tr>
                <td><%= mail_to preauthorization.email, preauthorization.email, target: "_blank" %></td>
                <td class="text-center"><% if preauthorization.admin %><i class="fas fa-check"></i><% end %></td>
                <td class="text-center"><% if preauthorization.contributor %><i class="fas fa-check"></i><% end %></td>
                <td class="text-center"><% if preauthorization.fulfilled %><i class="fas fa-check"></i><% end %></td>
                <th class="text-center"><%= link_to '<i class="fas fa-times"></i>'.html_safe, preauthorization, method: :delete, data: { confirm: 'Are you sure?' } %></th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> <!-- table responsive -->

    </div> <!-- preauthorization container -->
  </section>



  <section class="mb-5 my-"> <!-- users -->
    <h2 id="sm-header" class="text-center">SM to Approve</h2>
    <div id="sm-container">
      <% to_approve = 0 %>
      <% @contributors.each do |user| %>
        <% sm_not_blank = ( user.website_name && user.website_name != "" ) || ( user.website_url && user.website_url != "" ) || ( user.sm_facebook && user.sm_facebook != "" ) || ( user.sm_pinterest && user.sm_pinterest != "" ) || ( user.sm_instagram && user.sm_instagram != "" ) || ( user.sm_twitter && user.sm_twitter != "" ) || ( user.sm_youtube && user.sm_youtube != "" ) || ( user.sm_email && user.sm_email != "" ) || ( user.sm_other && user.sm_other != "" ) %>
        <% if sm_not_blank && user.sm_approved == false %>

          <%= link_to user_path(user) do %>
            <h3 class="font-script color-pink h1" style="margin-bottom: -10px"><%= user.first_name %> <%= user.last_name %></h3>
          <% end %>

          <%= render partial: "users/sm_links", locals: { user: user } %>

          <% to_approve += 1 %>
        <% end %>  <!-- if sm not blank -->
      <% end %>  <!-- contributors each do -->

      <% if to_approve == 0 %>
        <p>You have no SM links to approve at this time. Woohoo!</p>
      <% end %>
    </div> <!-- sm container -->
  </section>








  <section class="mb-5 my-"> <!-- users -->
    <h2 id="contributor-header" class="text-center">Contributors</h2>
    <div id="contributor-container">

      <% @contributors.order("created_at DESC").each do |user| %>
        <h3 class="thin" style="margin-bottom: 0px">
          <%= link_to user_path(user) do %>
            <span class="thin uppercase color-black"><%= user.first_name %> <%= user.last_name %></span>
          <% end %>
           ( <%= user.created_at.year %>
            <% if user.website_name != "" && user.website_url != "" %>
              , <%= link_to user.website_name, user.website_url, class: "thin color-black" %>
            <% end %>,
            <div id="toggle-sm-<%= user.id %>" class="h3" style="display: inline-block">🔍&nbsp;</div>)
        </h3>

        <div id="sm-container-<%= user.id %>" class="hidden outline-box z-depth-1 mb-3">
          <%= render partial: "users/sm_links", locals: { user: user } %>
        </div>

        <div class="pl-4">
          <% blogs = Blog.where(user_id: user.id) %>
          <% blogs.each do |blog| %>
            <%= render partial: "contributions/blog_line", locals: { blog: blog } %>
          <% end %>

        </div> <!-- contributor's stuff -->
      <% end %>

    </div> <!-- contributor container -->
  </section>









  <section class="text-center mb-5 my-"> <!-- users -->
    <h2 id="member-header">Members</h2>
    <div id="member-container">

      <div class="table-responsive" style="width: 100%">
        <table id="tableMembers" class="table thin table-striped table-bordered" width="100%">
          <thead>
            <tr>
              <th>Date</th>
              <th>Name</th>
              <th>Email</th>
              <th>Contributor</th>
              <th>X</th>
            </tr>
          </thead>

          <tbody class="text-left">
            <% @users.where(admin: false, contributor: false).order("created_at DESC").each do |user| %>
              <tr>
                <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
                <td><%= link_to user.full_name, user %></td>
                <td><%= user.email %></td>
                <td class="text-center"><% if user.contributor %><i class="fas fa-check"></i><% else %><%= link_to "Contributor!", make_contributor_path(user), method: :post %><% end %></td>
                <td><%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %><%= fa_icon "trash" %><% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> <!-- table responsive -->
    </div> <!-- member container -->

  </section>




</main>










<div class="modal fade" id="newPreauthorization" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create a New Preauthorization</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: "preauthorizations/form", locals: { preauthorization: @new_preauthorization } %>
      </div>
    </div>
  </div>
</div>








<%= content_for :additional_js do %>
  <script>
    $(document).ready(function () {
      $('#tableSuperusers').DataTable();
      $('#tableContributors').DataTable();
      $('#tablePreauthorizations').DataTable();
      $('#tableMembers').DataTable();

      $('.dataTables_length').addClass('bs-select');

      $("#superuser-header").click(function() {
        $("#superuser-container").toggleClass("hidden");
      })
      $("#preauthorization-header").click(function() {
        $("#preauthorization-container").toggleClass("hidden");
      })
      $("#sm-header").click(function() {
        $("#sm-container").toggleClass("hidden");
      })
      $("#contributor-header").click(function() {
        $("#contributor-container").toggleClass("hidden");
      })
      $("#member-header").click(function() {
        $("#member-container").toggleClass("hidden");
      })

      <% @contributors.each do |user| %>
        $("#toggle-sm-<%= user.id %>").click(function() {
          $("#sm-container-<%= user.id %>").toggleClass("hidden");
        })
      <% end %>

    });
  </script>
<% end %>