config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { registrations: 'registrations' }, path_prefix: "my"
  resources :users, only: [:show, :index, :edit, :update]

  get 'admin/dashboard'
  get 'admin/store_manager'
  get 'admin/blogs'
  get 'admin/freebies'
  get 'admin/drafts'
  get 'admin/users'
  get 'admin/categories'
  get 'admin/messages'

  get 'home/old'
  get 'home/old2'

  resources :categories
  resources :messages
  post "messages/:id/mark_answered" => "messages#mark_answered", as: "mark_answered"
  post "messages/:id/mark_unanswered" => "messages#mark_unanswered", as: "mark_unanswered"


  resources :meals
  post "meals/:id/favorite" => "meals#favorite", as: "favorite_meal"
  post "meals/:id/unfavorite" => "meals#unfavorite", as: "unfavorite_meal"

  post 'recipes/search' => 'recipes#index', as: "recipes_search"
  resources :recipes

  post "users/:id/approve_contributor" => "users#approve_contributor", as: "approve_contributor"
  post "users/:id/make_contributor" => "users#make_contributor", as: "make_contributor"
  post "users/:id/approve_sm" => "users#approve_sm", as: "approve_sm"

  get 'home/index'
  get 'home/house'
  get 'home/spouse'
  get 'home/kids'
  get 'home/self'
  get 'home/tools'
  get 'home/results'
  get 'home/redirect'

  resources :subcategories

  get 'tags/:tag', to: 'blogs#index', as: :tag
  resources :blogs do
    collection do
      get :autocomplete
    end
  end
  post "blogs/:id/approve_blog" => "blogs#approve_blog", as: "approve_blog"
  post "blogs/:id/unsubmit_blog" => "blogs#unsubmit_blog", as: "unsubmit_blog"
  patch "blogs/:id/update_goody" => "blogs#update_goody", as: "update_goody"
  patch "blogs/:id/toggle_category" => "blogs#toggle_category", as: "toggle_category"

  resources :tasks do
    collection do
      patch :sort
    end
  end
  post "tasks/:id/check_task" => "tasks#check_task", as: "check_task"
  post "tasks/:id/uncheck_task" => "tasks#uncheck_task", as: "uncheck_task"

  resources :occasions
  resources :people
  resources :gifts, only: [:edit, :update, :destroy, :show]

  resources :contributions
  post "contributions/:id/replied_contribution" => "contributions#replied_contribution", as: "replied_contribution"
  post "contributions/:id/unreplied_contribution" => "contributions#unreplied_contribution", as: "unreplied_contribution"

  resources :capsules do
    resources :capsule_items
  end

  resources :freebies
  resources :solutions

  resources :preauthorizations
  resources :sortings
  resources :groupings


  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get



end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  acts_as_taggable_on :tags

  belongs_to :user

  belongs_to :freebie, optional: true

  has_many :categorization_blogs
  has_many :categories, through: :categorization_blogs

  has_many :subcategorization_blogs
  has_many :subcategories, through: :subcategorization_blogs

  has_one_attached :image
  has_many_attached :pin_image
  has_one_attached :pdf

  searchkick text_start: [:title], suggest: [:title]

  def search_data
    {
      title: title,
      teaser: teaser,
      body: body,
      tag_list: tag_list
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
  def old
    @blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(8)
    @all_blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC")
    @featured_blogs = Blog.where(published: true, nondisplayed: false, featured_home: true).where("published_on <= ?", Date.today).order('published_on DESC').limit(4)
    @commented_blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('comments_count DESC').limit(8)
    @recent_blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(8)
    @homepageCSS = true
  end

  def old2
    # @headernav = true
    @blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(8)
    @all_blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC")
    @featured_blogs = Blog.where(published: true, nondisplayed: false, featured_home: true).where("published_on <= ?", Date.today).order('published_on DESC').limit(4)
    @commented_blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('comments_count DESC').limit(8)
    @recent_blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(8)
    @homepageCSS = true
  end

  def redirect
    if current_user
      redirect_to user_path(current_user)
    else
      redirect_to root_path
      flash[:notice] = "Uh oh.  Something appears to have gone wrong."
    end
  end

  def tools
  end

  def results
    query = params[:q].presence || "*"
    @blogs = Blog.where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('published_on DESC').search(query, suggest: true)
  end

  def house
    @all_house_blogs = Blog.where(category: "House").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC")
    @recent_blogs = Blog.where(category: "House").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @featured_blogs = Blog.where(category: "House", published: true, nondisplayed: false, featured_category: true).where("published_on <= ?", Date.today).order('published_on DESC').limit(4)
    @commented_blogs = Blog.where(category: "House").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('comments_count DESC').limit(3)
    @recent_blogs = Blog.where(category: "House").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @other_blogs = Blog.where(category: "House").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").offset(3).all
    @tags = Blog.tag_counts_on(:tags)
    @subcategories = Subcategory.where(category: "House")
  end

  def spouse
    @all_spouse_blogs = Blog.where(category: "Spouse").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC")
    @recent_blogs = Blog.where(category: "Spouse").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @featured_blogs = Blog.where(category: "Spouse", published: true, nondisplayed: false, featured_category: true).where("published_on <= ?", Date.today).order('published_on DESC').limit(4)
    @commented_blogs = Blog.where(category: "Spouse").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('comments_count DESC').limit(3)
    @recent_blogs = Blog.where(category: "Spouse").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @other_blogs = Blog.where(category: "Spouse").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").offset(3).all
    @tags = Blog.tag_counts_on(:tags)
    @subcategories = Subcategory.where(category: "Spouse")
  end

  def kids
    @all_kids_blogs = Blog.where(category: "Kids").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC")
    @recent_blogs = Blog.where(category: "Kids").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @featured_blogs = Blog.where(category: "Kids", published: true, nondisplayed: false, featured_category: true).where("published_on <= ?", Date.today).order('published_on DESC').limit(4)
    @commented_blogs = Blog.where(category: "Kids").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('comments_count DESC').limit(3)
    @recent_blogs = Blog.where(category: "Kids").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @other_blogs = Blog.where(category: "Kids").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").offset(3).all
    @tags = Blog.tag_counts_on(:tags)
    @subcategories = Subcategory.where(category: "Kids")
  end

  def self
    @all_self_blogs = Blog.where(category: "Self").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC")
    @recent_blogs = Blog.where(category: "Self").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @featured_blogs = Blog.where(category: "Self", published: true, nondisplayed: false, featured_category: true).where("published_on <= ?", Date.today).order('published_on DESC').limit(4)
    @commented_blogs = Blog.where(category: "Self").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order('comments_count DESC').limit(3)
    @recent_blogs = Blog.where(category: "Self").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").limit(3)
    @other_blogs = Blog.where(category: "Self").where("published_on <= ?", Date.today).where(published: true, nondisplayed: false).order("published_on DESC").offset(3).all
    @tags = Blog.tag_counts_on(:tags)
    @subcategories = Subcategory.where(category: "Self")

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about.html.erb
<div class="container text-white">
  <h2 class="section-title">About The Stay Sane Mom</h2>
  <div class="row">
    <div class="col-lg-4 text-center">
      <%= image_tag "liz-bayardelle-stay-sane-mom.jpg", class: "about-me-image" %>
      <%= link_to "The Stay Sane Mom Mission", static_path(:AboutMe), class: "btn btn-grey" %>
    </div> <!-- col -->
    <div class="col-lg-8">
      <div class="tilted-card">
        <h3>
          Hi I'm Mom...I mean Liz.
        </h3>
        <p>
          Hello there!  And welcome to The Stay Sane Mom! My name is Liz and I'm the wife/mom to a teenage stepdaughter (and Instagram aficionado), a sparkle-clad kidnado, a newly-toddler boy (and professional raccoon noise impersonator), two large canine furkids, a bunny of unusual size, and (if I don't vacuum daily) a herd of irascible dustbunnies.
        </p>
        <p>
          My "nights and naptimes" alterego is an author, freelance digital consultant, workout nut, avid bookworm, and has a PhD in Business Psychology.
        </p>
        <p>
          Oh yeah, I'm also the founder of The Stay Sane Mom.
        </p>
        <p>
          We're here to help you as a mom.  Whether that's giving you research-based systems to help your tribe run smoother, printable tools to help you stay organized, or just a wheelbarrow-load of sarcasm to get you through until bedtime...we've got your back, Mama.
        </p>
        <h4 class="h2 text-right font-script color-pink" style="margin-right: 30%">
          Stay Sane, Liz
        </h4>

      </div> <!-- tilted-card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div> <!-- container -->

app/views/home/_services.html.erb
<h2 class="display-2 lh-1">
  How We Help
</h2>

<p class="w-responsive mx-auto mb-5">
  We can't come watch your kids for you.  Or clean your house.  
  <br>
  But we do have three easy ways to make your life better.
</p>

<div class="row">

  <div class="col-sm-4 mb-4">
    <div class="card collection-card z-depth-1-half">
      <div class="view zoom">
        <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Callouts/tools.jpg" class="img-fluid"
          alt="">
        <div class="stripe dark">
          <%= link_to page_path("tools") do %>
            <p>Online<br class="d-lg-none"> Tools
              <i class="fas fa-angle-right"></i>
            </p>
          <% end %>
        </div> <!-- stripe -->
      </div> <!-- Card image -->
    </div> <!-- Collection card -->
  </div> <!-- Grid column -->

  <div class="col-sm-4 mb-4">
    <div class="card collection-card z-depth-1-half">
      <div class="view zoom">
        <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Callouts/resources.jpg" class="img-fluid"
          alt="">
        <div class="stripe dark">
          <%= link_to freebies_path do %>
            <p>Quick<br class="d-lg-none"> Fixes
              <i class="fas fa-angle-right"></i>
            </p>
          <% end %>
        </div> <!-- stripe -->
      </div> <!-- Card image -->
    </div> <!-- Collection card -->
  </div> <!-- Fourth column -->

  <div class="col-sm-4 mb-4">
    <div class="card collection-card z-depth-1-half">
      <div class="view zoom">
        <img src="https://staysanemom.s3-us-west-1.amazonaws.com/Callouts/store.jpg" class="img-fluid"
          alt="">
        <div class="stripe dark">
          <%= link_to solutions_path do %>
            <p>Full<br class="d-lg-none"> Systems
              <i class="fas fa-angle-right"></i>
            </p>
          <% end %>
        </div> <!-- stripe -->
      </div> <!-- Card image -->
    </div> <!-- Collection card -->
  </div> <!-- Grid column -->

</div> <!-- Grid row -->

app/views/home/index-old.html.erb
<!-- page-specific content -->
  <% title "The Stay Sane Mom" %>
  <%= content_for :head do %>
    <meta name="description" content="Helping overworked moms keep clean house, a healthy marriage, balanced kids, and stay sane on top of it all." />
  <% end %>
<!-- page-specific content -->

<div class="header-frame frame" style="background-image: url(<%= asset_path "stay_sane_mom.jpg" %>)" role="img" aria-label="Overwhelmed mom acting like she's tearing her hair out."><div class="image-overlay-white"><div class="inner-frame border-neutral"></div></div></div>

<div class="over-frame-text">
  <div class="container">
    <h1 class="color-black">Need more sanity?</h1>
    <h4 class="text-center">We help you master your domain,<br .>so you can be more than just "mom".</h4>
  </div> <!-- container -->
  <div class="over-frame-bottom-row">
    <div class="container">
      <div class="text-center">
        <div class="half-buffer"></div>
          <a class="btn my-btn-outline-secondary hero-button" data-formkit-toggle="cd10cef13b" href="https://pages.convertkit.com/2d8e722187/31069c0b92">Your Support System Awaits</a>
        <div class="buffer"></div>
      </div> <!-- text center -->
    </div> <!-- container -->
  </div> <!-- over-frame-text -->
</div> <!-- over-frame-text -->

<div class="padded bg-solid-spouse">
  <div class="container">
    <h2 class="text-center boldest d-lg-none">New! Custom designed planners for&nbsp;your&nbsp;crazy&nbsp;life!</h2>
    <div class="half-buffer d-none d-lg-block"></div>
    <div class="row">
      <div class="col-sm-3">
        <%= image_tag "your-name-here-planner.png", style: "max-width: 100%;" %>
      </div> <!-- small col -->
      <div class="col-sm-9">
        <h2 class="text-center boldest d-none d-lg-block">New! Custom designed planners for&nbsp;your&nbsp;crazy&nbsp;life!</h2>
        <div class="half-buffer d-none d-lg-block"></div>
        <h5>Can everything you do fit on the mundane pages of the average planner?</h5>
        <h5>Me neither.</h5>
        <h5>Get a planner that's designed 100% just for your specific brand of insanity.</h5>
        <div class="half-buffer d-none d-lg-block"></div>
        <h3 class="text-center d-none d-lg-block"><%= link_to "Design your custom planner now!", static_path(:planners), class: "boldest color-white" %></h3>
      </div> <!-- small col -->
    </div> <!-- row -->
    <h3 class="text-center d-lg-none"><%= link_to "Design your custom planner now!", static_path(:planners), class: "boldest color-white" %></h3>
  </div> <!-- container -->
</div> <!-- stripe bg -->


  <div class="container">

    <div class="category-callouts">
        <h2 class="text-center script-header">Get Help with Your...</h2>

        <div class="row">
            <div class="col-sm-6 col-lg-3"><div class="category-div border-house transparent-hover house card">
              <%= link_to home_house_path do %>
                <div class="frame category-frame" style="background-image: url(<%= asset_path "keep-house-clean.jpg" %>)"><div class=""></div></div>
                <div class="text">
                  <h3 class="color-house text-center">House</h3>
                  <p>Let's face it, we all wish we could keep a cleaner house.  No one likes coming home to laundry mountain and a dust bunny brigade.</p>
                  <p>Here you can learn how to keep the chaos at bay.</p>
                </div> <!-- text -->
                <h5 class="text-center"><%= link_to "Clean My House", home_house_path, class: "color-house" %></h5>
              <% end %>
            </div></div> <!-- category div / col div -->

            <div class="col-sm-6 col-lg-3"><div class="category-div border-spouse transparent-hover spouse">
              <%= link_to home_spouse_path do %>
              <div class="frame category-frame" style="background-image: url(<%= asset_path "keep_marriage_healthy.jpg" %>)"><div class=""></div></div>
              <div class="text">
                <h3 class="color-spouse text-center font-script">Spouse</h3>
                <p>It's hard to pay attention to your marriage when jobs, chores, obligations, and all these tiny humans keep demanding things of us.</p>
                <p>These tools should help you keep a healthy marriage in spite of everything else you have going on.</p>
              </div> <!-- text -->
              <h5 class="text-center"><%= link_to "Build My Marriage", home_spouse_path, class: "color-spouse" %></h5>
              <% end %>
            </div></div> <!-- category div / col div -->

            <div class="col-sm-6 col-lg-3"><div class="category-div border-kids transparent-hover kids">
              <%= link_to home_kids_path do %>
              <div class="frame category-frame" style="background-image: url(<%= asset_path "raise_balanced_happy_kids.jpg" %>)"><div class=""></div></div>
              <div class="text">
                <h3 class="color-kids text-center">Kids</h3>
                <p>Kids. Progeny. Tiny bulldozers that terrorize your (previously-clean) house and leave nothing but mayhem in their wake.</p>
                <p>Here are your resources to raise balanced, happy, well-rounded kids without driving yourself crazy.</p>
              </div> <!-- text -->
              <h5 class="text-center"><%= link_to "Raise Happy Kids", home_kids_path, class: "color-kids" %></h5>
              <% end %>
            </div></div> <!-- category div / col div -->

            <div class="col-sm-6 col-lg-3 "><div class="category-div border-self transparent-hover neutral">
              <%= link_to home_self_path do %>
              <div class="frame category-frame" style="background-image: url(<%= asset_path "take-care-of-yourself.jpg" %>)"><div class=""></div></div>
              <div class="text">
                <h3 class="color-self text-center">Self</h3>
                <p>You wear many different hats throughout the course of the day. (Mom, chauffeur, executive assistant, chef, the list goes on...)  However, you are (believe it or not) also allowed to take care of yourself as a person.</p>
                <p>This section is for you if you're having trouble remembering who you were before you were "Mom".</p>
              </div> <!-- text -->
              <h5 class="text-center"><%= link_to "Stay Sane", home_self_path, class: "color-self" %></h5>
              <% end %>
            </div></div> <!-- category div / col div -->
        </div> <!-- row -->
    </div> <!-- category callouts -->
</div> <!-- container -->

<div class="about-me bg-neutral">
  <div class="container" style="padding: 0px 0 20px 0">
    <h2 class="text-center script-header" style="padding-top: 20px">About Me</h2>
    <div class="row">
      <div class="col-sm-4 text-center">
        <%= image_tag "liz-bayardelle-stay-sane-mom.jpg", class: "rounded-image" %>
      </div> <!-- col -->
      <div class="col-sm-8" style="padding: 0 30px 0 30px">
        <p>Hello there!  My name is Liz, but I also answer to "Hey Honey?", "Mom", or (more often) "Mom Mom Mom MAHM!".</p>
        <p>I'm the wife to an amazing man and mom to a preteen stepdaughter (and Instagram aficionado), a sparkle-clad toddlernado, two large canine furkids, a bunny of unusual size, and (if I don't vacuum daily) a herd of dustbunnies. My alterego by night is a PhD candidate, freelance consultant, web developer, and graphic designer, workout nut, entrepreneur, writer, and avid bookworm.</p>
        <h5><%= link_to "More About the Stay Sane Mom...", static_path(:AboutMe) %></h5>
      </div> <!-- col -->
    </div> <!-- row -->
  </div> <!-- container -->
</div> <!-- about me -->

<div class="buffer"></div>

<div class="container small-boxes">
  <h2 class="font-script text-center color-neutral">What's New?</h2>

  <div class="row">

    <div class="col-md-6 col-lg-4">
      <h3 class="text-center">Most Popular Blogs</h3>
      <% @commented_blogs.each do |blog| %>
        <%= render partial: "layouts/blogcard", locals: { blog: blog } %>
      <% end %>
      <h5 class="text-center font-script"><%= link_to "See " + (@all_blogs.count - 3).to_s + " More Posts...", blogs_path, class: "font-script" %></h5>
    </div> <!-- popular blogs third -->

    <div class="col-md-6 col-lg-4">
      <h3 class="text-center">Popular Tools</h3>

        <%= link_to tasks_path do %>
          <div class="blog-card">
              <div class="other transparent-hover neutral">
                <div class="flag">Tool</div>
                <div class="small-blog-frame" style="background-image: url(<%= asset_path "house-task-organizer.jpg" %>)">
                    <div class="image-overlay-neutral"></div>
                </div>
                <div class="height blog-text">
                  <h5>House Task Organizer</h5>
                  <p>Keep your house clean with one-time, daily, weekly, and monthly task lists.</p>
                </div> <!-- blog-text -->
              </div> <!-- end case div -->
            </div> <!-- blog card/col -->
          <% end %>

          <%= link_to capsules_path do %>
            <div class="blog-card">
                <div class="other transparent-hover neutral">
                  <div class="flag">Tool</div>
                  <div class="small-blog-frame" style="background-image: url(<%= asset_path "yearly-photo-time-capsules.jpg" %>)">
                      <div class="image-overlay-neutral"></div>
                  </div>
                  <div class="height blog-text">
                    <h5>Photo Time Capsule</h5>
                    <p>Create year-by-year time capsules to watch your family grow.</p>
                  </div> <!-- blog-text -->
                </div> <!-- end case div -->
              </div> <!-- blog card/col -->
            <% end %>

        <%= link_to people_path do %>
          <div class="blog-card">
              <div class="other transparent-hover neutral">
                <div class="flag">Tool</div>
                <div class="small-blog-frame" style="background-image: url(<%= asset_path "keep-track-of-family-dates-and-events.jpg" %>)">
                    <div class="image-overlay-neutral"></div>
                </div>
                <div class="blog-text">
                  <h5>Birthday Tracker</h5>
                  <p>Input birthdays, anniversaries, and more.  Never forget an important date again.</p>
                </div> <!-- blog-text -->
              </div> <!-- end case div -->
            </div> <!-- blog card/col -->
          <% end %>

        <%= link_to occasions_path do %>
          <div class="blog-card">
              <div class="other transparent-hover neutral">
                <div class="flag">Tool</div>
                <div class="small-blog-frame" style="background-image: url(<%= asset_path "gift-planner.jpg" %>)">
                    <div class="image-overlay-neutral"></div>
                </div>
                <div class="blog-text">
                  <h5>Gift Planner</h5>
                  <p>Plan all your major holidays with our automated gift planner.</p>
                </div> <!-- blog-text -->
              </div> <!-- end case div -->
            </div> <!-- blog card/col -->
          <% end %>
      <h5 class="text-center font-script"><%= link_to "See More Tools...", static_path(:tools), class: "font-script" %></h5>
    </div> <!-- third -->

    <div class="col-md-12 col-lg-4">
      <h3 class="text-center">Newest Blogs</h3>
      <% @recent_blogs.each do |blog| %>
        <%= render partial: "layouts/blogcard", locals: { blog: blog } %>
      <% end %>
      <h5 class="text-center font-script"><%= link_to "See Older Posts...", blogs_path, class: "font-script" %></h5>
    </div> <!-- third -->
  </div> <!-- row -->
</div> <!-- what's new container -->

<div class="buffer"></div>

<div class="container">
  <h2 class="text-center font-script">Get Your Read On</h2>
  <div class="d-none d-md-block">
    <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=13&l=ez&f=ifr&linkID=526f15239e6428e05b1f619edab282e1&t=thestaysane00-20&tracking_id=thestaysane00-20" width="468" height="60" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
  </div>
  <div class="d-block d-md-none">
    <iframe src="//rcm-na.amazon-adsystem.com/e/cm?o=1&p=12&l=ez&f=ifr&linkID=3a935daae9cd59d53948557f9d763e70&t=thestaysane00-20&tracking_id=thestaysane00-20" width="300" height="250" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0"></iframe>
  </div>
</div> <!-- container -->



  <!-- form itself -->
  <div id="convertkitPopup" class="white-popup mfp-hide">
    <script async data-uid="fcce48a626" src="https://f.convertkit.com/fcce48a626/999d19a7ee.js"></script>
  </div>




<%= content_for :additional_js do %>
  <script type="text/javascript">
    $(document).ready(function() {
        $('.height').matchHeight();
        $('.category-div').matchHeight();
        $('.blog-text').matchHeight();
        $('.blog-teaser').matchHeight();
        $('.blog-description').matchHeight();
        $('.blog-info').matchHeight();
        $('.tool-box-text').matchHeight();
        $('.open-popup-link').magnificPopup({
          type:'inline',
          midClick: true // Allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source in href.
        });
        $('.hero-button').click(function() {
            ga('send', 'event', 'Subscription', 'Hero Button Subscription', 'Homepage Hero Button Subscription');
        });
      });
  </script>
<% end %>

app/views/home/redirect.html.erb
<main class="text-center py-5 my-5">
  <h1 class="thin">
    Stay tuned to be redirected to your account or click <%= link_to "here", user_path(current_user) %> to expedite the process.
  </h1>
</main>