config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, :controllers => { registrations: 'registrations' }, path_prefix: "my"
  resources :users, only: [:show, :index, :edit, :update]

  get 'admin/dashboard'
  get 'admin/store_manager'
  get 'admin/blogs'
  get 'admin/freebies'
  get 'admin/drafts'
  get 'admin/users'
  get 'admin/categories'
  get 'admin/messages'

  get 'home/old'
  get 'home/old2'

  resources :categories
  resources :messages
  post "messages/:id/mark_answered" => "messages#mark_answered", as: "mark_answered"
  post "messages/:id/mark_unanswered" => "messages#mark_unanswered", as: "mark_unanswered"


  resources :meals
  post "meals/:id/favorite" => "meals#favorite", as: "favorite_meal"
  post "meals/:id/unfavorite" => "meals#unfavorite", as: "unfavorite_meal"

  post 'recipes/search' => 'recipes#index', as: "recipes_search"
  resources :recipes

  post "users/:id/approve_contributor" => "users#approve_contributor", as: "approve_contributor"
  post "users/:id/make_contributor" => "users#make_contributor", as: "make_contributor"
  post "users/:id/approve_sm" => "users#approve_sm", as: "approve_sm"

  get 'home/index'
  get 'home/house'
  get 'home/spouse'
  get 'home/kids'
  get 'home/self'
  get 'home/tools'
  get 'home/results'
  get 'home/redirect'

  resources :subcategories

  get 'tags/:tag', to: 'blogs#index', as: :tag
  resources :blogs do
    collection do
      get :autocomplete
    end
  end
  post "blogs/:id/approve_blog" => "blogs#approve_blog", as: "approve_blog"
  post "blogs/:id/unsubmit_blog" => "blogs#unsubmit_blog", as: "unsubmit_blog"
  patch "blogs/:id/update_goody" => "blogs#update_goody", as: "update_goody"
  patch "blogs/:id/toggle_category" => "blogs#toggle_category", as: "toggle_category"

  resources :tasks do
    collection do
      patch :sort
    end
  end
  post "tasks/:id/check_task" => "tasks#check_task", as: "check_task"
  post "tasks/:id/uncheck_task" => "tasks#uncheck_task", as: "uncheck_task"

  resources :occasions
  resources :people
  resources :gifts, only: [:edit, :update, :destroy, :show]

  resources :contributions
  post "contributions/:id/replied_contribution" => "contributions#replied_contribution", as: "replied_contribution"
  post "contributions/:id/unreplied_contribution" => "contributions#unreplied_contribution", as: "unreplied_contribution"

  resources :capsules do
    resources :capsule_items
  end

  resources :freebies
  resources :solutions

  resources :preauthorizations
  resources :sortings
  resources :groupings


  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get



end

app/models/contribution.rb
class Contribution < ApplicationRecord
  
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :destroy]
  before_action :admin_only, only: [:index, :destroy]
  invisible_captcha only: [:create, :update], honeypot: :subtitle

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.all
    @blogs = Blog.all
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
    @headernav = true
  end

  # GET /contributions/new
  def new
    @headernav = true
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)

    respond_to do |format|
      if @contribution.save
        GuestPostMailer.post_idea(@contribution).deliver
        format.html { redirect_to root_path, notice: 'Your idea has been sent!  Be prepared to hear from us within 48 hours!' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admin_only
    unless current_user && current_user.admin
      redirect_to root_path, notice: 'Sorry, you have to be an admin to do that!'
    end
  end

  def replied_contribution
      @contribution = Contribution.find(params[:id])
      GuestPostMailer.idea_accepted(@contribution).deliver
      p = Preauthorization.new(email: @contribution.email, contributor: true)
      p.save
      if @contribution.update_attributes(responded: true)
          respond_to do |format|
            format.html { redirect_to contributions_url, notice: "Boom! It's been approved, emails have been sent, magic has occurred." }
            format.json { head :no_content }
          end
      else
          redirect_to contributions_path
          flash[:warning] = "Oops! Something went wrong!"
      end
  end

  def unreplied_contribution
      @contribution = Contribution.find(params[:id])
      if @contribution.update_attributes(responded: false)
          respond_to do |format|
            format.html { redirect_to contributions_url, notice: "Uh oh, guess you didn't reply after all." }
            format.json { head :no_content }
          end
      else
          redirect_to contributions_path
          flash[:warning] = "Oops! Something went wrong!"
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(
        :name,
        :email,
        :category,
        :idea,
        :blog,
        :prev_published,
        :terms,
        :comments,
        :responded,
        :archived
      )
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_blog_line.html.erb
<p style="line-height: 1"><small>
  <%= link_to blog.title, blog_path(blog), class: "color-pink" %>
  <br>
  <%= link_to blog.user.first_name + " " + blog.user.last_name, user_path(blog.user), class: "thin color-black" %>

  &nbsp;&nbsp;|&nbsp;&nbsp;

  <% if blog.published %>
    Published
  <% elsif !blog.published && blog.approved %>
    Approved
  <% elsif !blog.approved && blog.submitted %>
    Submitted
  <% else %>
    Draft
  <% end %>

  &nbsp;&nbsp;|&nbsp;&nbsp;

  <%= link_to edit_blog_path(blog) do %><%= fa_icon "pencil-alt" %><% end %>
  <%= link_to blog, method: :delete, data: { confirm: 'Are you sure?' } do %><%= fa_icon "trash" %><% end %>
</small></p>

app/views/contributions/_form.html.erb
<h2 class="text-center font-script color-neutral">Guest Post Idea Submission</h2>

<div class="container">
  <%= simple_form_for(@contribution) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <%= f.invisible_captcha :subtitle %>

    <div class="form-inputs">
      <div class="form-group">
        <%= f.input :name, required: true %>
      </div> <!-- form group -->
      <div class="form-group">
        <%= f.input :email, required: true %>
      </div> <!-- form group -->
      <div class="form-group">
        <%= f.label "Your Blog URL", required: true %>
        <%= f.text_field :blog, class: "form-control", required: true, placeholder: "https://www.yourbloghere.com" %>
      </div> <!-- form group -->
      <div class="form-group">
        <%= f.input :category, input_html: {class: 'browser-default'}, collection: [['General', 'General'], ['House', 'House'], ['Spouse', 'Spouse'], ['Kids', 'Kids'], ['Self', 'Self'], ['Other', 'Other']] %>
      </div>
      <div class="form-group">
        <%= f.label "Your Guest Post Idea" %>
        <%= f.text_area :idea, class: "form-control" %>
      </div> <!-- form group -->
      <div class="form-group">
        <%= f.label "Other Comments" %>
        <%= f.text_area :comments, class: "form-control" %>
      </div> <!-- form group -->
      <div class="checkbox-inline">
        <%= f.input :prev_published, required: true, label: "This idea has not been published anywhere else" %>
      </div>
      <div class="checkbox-inline">
        <%= f.input :terms, required: true, label: "I agree to the rules stated above" %>
      </div> <!-- form group -->
    </div>

    <div class="half-buffer"></div>

    <div class="text-center">
      <%= f.button :submit, "Send Idea", class: "btn btn-outline-danger submit-comment" %>
    </div>
  <% end %>
</div> <!-- container -->

<%= content_for :additional_js_partial do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('.submit-comment').click(function() {
          ga('send', 'event', 'Participation', 'Guest Post Idea', 'Guest Post Idea');
      });
    });
  </script>
<% end %>

app/views/contributions/index.html.erb
<header class="header-stripe">
  <h1 class="display-4 thin">Guest Post Dashboard</h1>
</header>

<main class="container mt-3">


  <h2 id="ideas-header" class="font-script color-pink mt-4 text-center">Guest Post Ideas</h2>
  <section id="ideas-container" class="container mb-5">

    <% unresponded = @contributions.where(responded: false) %>
    <% responded = @contributions.where(responded: true) %>

    <% if unresponded.count != 0 %>
      <h3 id="needing-replies-header" class="thin uppercase mb-2 text-center">Ideas Needing Replies</h3>
      <div id="needing-replies-container">
        <table class="lined-table">
          <tbody>
            <% unresponded.each do |contribution| %>
              <tr>
                <td style="border-right: none" class="color-pink">
                  <%= link_to replied_contribution_path(contribution), class: "color-pink", method: :post do %><%= fa_icon "thumbs-up" %><% end %>
                  <%= link_to contribution, method: :delete, data: { confirm: 'Are you sure?' } do %><%= fa_icon "trash" %><% end %>
                </td>
                <td style="border-left: none">
                  <span class="color-pink"><strong><%= contribution.name %></strong></span><br />
                  <%= mail_to contribution.email %><br />
                  <%= contribution.blog %>
                </td>
                <td>
                  <span class="color-pink"><strong>For the <%= contribution.category %> Category</strong></span><br />
                  <%= contribution.idea %><% if contribution.comments != "" %><br />
                  <em>Comments: <%= contribution.comments %><% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>You currently have no outstanding guest post ideas.</p>
      <% end %>
    </div> <!-- needing replies container -->



    <% if responded.count != 0 %>
      <h3 id="replied-header" class="thin uppercase text-center mt-5">Ideas Already Replied</h3>
      <div id="replied-container" class="hidden">
        <% responded.each do |contribution| %>
          <p style="line-height: 1.2"><small>
            <span class="color-pink"><strong><%= contribution.name %></strong></span> (<%= link_to contribution.blog %>)<br />
            <%= contribution.idea %><% if contribution.comments != "" %><br />
            <em>Comments: <%= contribution.comments %><% end %>
            <br>
            <%= link_to unreplied_contribution_path(contribution), method: :post do %>Mark&nbsp;Unreplied<% end %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Delete', contribution, method: :delete, data: { confirm: 'Are you sure?' } %>
          </small></p>
        <% end %>
      <% else %>
        <p>You currently have no outstanding guest post ideas.</p>
      <% end %>
    </div> <!-- replied container -->


  </section>



  <h2 id="existing-header" class="font-script color-pink mt-4 text-center">Existing Guest Posts</h2>
  <section id="existing-container" class="mb-5 container">

    <% @wip_blogs = [] %>
    <% @submitted_blogs = [] %>
    <% @approved_blogs = [] %>
    <% @published_blogs = [] %>
    <% @blogs.each do |blog| %>
      <% if blog.user.contributor && !blog.user.admin %>
        <% if !blog.submitted %>
          <% @wip_blogs << blog %>
        <% end %>
        <% if blog.submitted && !blog.approved %>
          <% @submitted_blogs << blog %>
        <% end %>
        <% if blog.approved && !blog.published %>
          <% @approved_blogs << blog %>
        <% end %>
        <% if blog.published && blog.published_on %>
          <% if blog.published_on >= Date.today %>
            <% @published_blogs << blog %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>

    <h3 id="wip-header" class="section-header">WIP Guest Posts (<%= @wip_blogs.count %>)</h3>
    <div id="wip-container" class="section-container">
      <% @wip_blogs = Blog.where.not(user_id: 1).where(submitted: false) %>
      <% if @wip_blogs.count != 0 %>
        <% @wip_blogs.each do |blog| %>
          <%= render partial: "contributions/blog_line", locals: { blog: blog } %>
        <% end %>
      <% else %>
        <p>You currently have no WIP guest posts.</p>
      <% end %>
    </div> <!-- section container -->

    <h3 id="submitted-header" class="section-header">Submitted Guest Posts (<%= @submitted_blogs.count %>)</h3>
    <div id="submitted-container" class="section-container">
      <% @submitted_blogs = Blog.where.not(user_id: 1).where(submitted: true, approved: false, published: false) %>
      <% if @submitted_blogs.count != 0 %>
        <% @submitted_blogs.each do |blog| %>
          <%= render partial: "contributions/blog_line", locals: { blog: blog } %>
        <% end %>
      <% else %>
        <p>You currently have no submitted guest posts.</p>
      <% end %>
    </div> <!-- section container -->

    <h3 id="approved-header" class="section-header">Approved/Scheduled Guest Posts (<%= @approved_blogs.count %>)</h3>
    <div id="approved-container" class="section-container">
      <% @approved_blogs = Blog.where.not(user_id: 1).where(submitted: true, approved: true, published: false) %>
      <% if @approved_blogs.count != 0 %>
        <% @approved_blogs.each do |blog| %>
          <%= render partial: "contributions/blog_line", locals: { blog: blog } %>
        <% end %>
      <% else %>
        <p>You currently have no accepted guest posts.</p>
      <% end %>
    </div> <!-- section container -->

    <h3 id="published-header" class="section-header">Published Guest Posts (<%= @published_blogs.count %>)</h3>
    <div id="published-container" class="section-container">
      <% @published_blogs = Blog.where.not(user_id: 1).where(published: true) %>
      <% if @published_blogs.count != 0 %>
        <% @published_blogs.each do |blog| %>
        <%= link_to blog.title, blog_path(blog), class: "color-pink" %>
        (<%= link_to blog.user.first_name + " " + blog.user.last_name, user_path(blog.user) %>)<br>
        <% end %>
      <% else %>
        <p>You currently have no published guest posts.</p>
      <% end %>
    </div> <!-- section container -->

  </section>





<%= content_for :additional_js do %>
  <script type="text/javascript">
    $(document).ready(function () {
      $("#wip-header").click(function() {
        $("#wip-container").toggleClass("hidden");
      })
      $("#submitted-header").click(function() {
        $("#submitted-container").toggleClass("hidden");
      })
      $("#approved-header").click(function() {
        $("#approved-container").toggleClass("hidden");
      })
      $("#published-header").click(function() {
        $("#published-container").toggleClass("hidden");
      })
      $("#ideas-header").click(function() {
        $("#ideas-container").toggleClass("hidden");
      })
      $("#existing-header").click(function() {
        $("#existing-container").toggleClass("hidden");
      })
      $("#needing-replies-header").click(function() {
        $("#needing-replies-container").toggleClass("hidden");
      })
      $("#replied-header").click(function() {
        $("#replied-container").toggleClass("hidden");
      })
    });
  </script>
<% end %>

app/views/contributions/new.html.erb
<!-- page-specific content -->
  <% title "Guest Posts | SSM" %>
  <%= content_for :head do %>
    <meta name="description" content="Contribute a guest blog post to The Stay Sane Mom." />
  <% end %>
<!-- page-specific content -->

<div class="header-frame frame" style="background-image: url(<%= asset_path "contribute-a-guest-post.jpg" %>)"><div class="image-overlay-neutral"><div class="inner-frame border-neutral"></div></div></div>
<div class="over-frame-text">
  <div class="container">
    <h1 class="text-center">Want to write a guest post?</h1>
  </div>
</div>

<div class="half-buffer"></div>
<div class="container">
  <h2>Contribute to the Stay Sane Mom!</h2>
  <p>Thank you so much for your interest in guest posting on <em>The Stay Sane Mom</em>!  I love hearing from different moms because everyone's crazy, ridiculous journey is so unique.</p>

  <h2>A Few Quick Rules</h2>
  <p>In order to make sure my readers get the quality and consistency they deserve, I have a few quick rules (guidelines, really) for guest posters.  We'll make this quick, I promise.</p>
  <ul>
    <li><p>I can't accept 100% of the submissions I get on this site, but I will read and respond to everything that gets submitted within 48 hours.</p></li>
    <li><p>Once a submission is approved, I'll work with the individual author on a publishing timeline.  It could happen almost immediately or it could take a few weeks to get the kinks ironed out.  Ultimately, it won't go up until it's "ready".  If we're having trouble with your post I'll do everything I can to work with you to get it "ready", but I won't post anything that doesn't pass muster, so to speak.</p></li>
    <li><p>As a self-admitted grammar nut, I reserve the right to edit grammar, spelling, punctuation, syntax, and use of keywords/SEO stuff, as well as approving any links included in the article.</p></li>
    <li><p>As a guest poster, you should be ready and willing to promote your post on your blog/social media/email list/carrier pigeon tribe/etc.</p></li>
    <li><p>Link sharing is a must!  A do-follow link to your site will be included as part of your short "author bio", and it's a best practice to include a do-follow list to your published guest post on your blog.  (Usually this happens on a "My Guest Appearances" or "As Seen On" page.)</p></li>
    <li><p>Guest posts are different than sponsored posts.  If you want me to do a product or service review, please email me at <%= mail_to "liz@theStaySaneMom.com" %>.</p></li>
  </ul>

  <h2>Post Specifics</h2>
  <p>Once you get the go ahead on your idea, here are the basic specifics for a guest post.</p>
  <ul>
    <li><p>Post should have one topic and stick with it.  (i.e. If you're writing about tricking kids into eating their vegetables, don't start to wander off and start talking about house cleaning.)</p></li>
    <li><p>Posts can't have been published anywhere before.  Similarly, you can always link to your published post, but the same content can't be reused anywhere else without my written consent.</p></li>
    <li><p>Posts should include specific keyword(s).  Please include long- or short-tailed keywords with your post.</p></li>
    <li><p>Posts shouldn't be shorter than 750 words.</p></li>
    <li><p>Format your post using headers, bullets, etc.  Don't go crazy with the bold, italics, underlining, and capitalization.  A little is okay, too much is distracting.</p></li>
    <li><p>No affiliate links in guest posts, please.  You can post links to your site in your article where they're appropriate, but I reserve the final judgement call for links in general and specifically on no-follow versus do-follow links.  You always get the do-follow link to your site in your author bio.  You can also include any social media links you want in your author bio.</p></li>
  </ul>

  <p>Thank you again for your interest in guest posting!  Fill out the submission form below and I'll get back to you about your idea in 48(ish) hours.</p>

  <div class="half-buffer"></div>

  <div class="border-neutral" style="padding: 30px">
    <%= render 'form', contribution: @contribution %>
  </div>
</div> <!-- container -->



<%= content_for :additional_js do %>
  <script type="text/javascript">
    $(function() {
      $('.content-box').matchHeight();
    });
  </script>
<% end %>